// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDStE1XJdvv1Fbbz6yVnI6kXGeEqOEeeBg',
    appId: '1:230534942983:web:7383b2c155de959c80b5a2',
    messagingSenderId: '230534942983',
    projectId: 'web-admin-panel-5ebfb',
    authDomain: 'web-admin-panel-5ebfb.firebaseapp.com',
    storageBucket: 'web-admin-panel-5ebfb.firebasestorage.app',
    measurementId: 'G-B3KYJ5G7PT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBin8gR-WgrJqDyAJZB0Q0lo91CFDD5d9g',
    appId: '1:230534942983:android:cd85db33d736866e80b5a2',
    messagingSenderId: '230534942983',
    projectId: 'web-admin-panel-5ebfb',
    storageBucket: 'web-admin-panel-5ebfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaTc5G6BfjO56jmGPWKA7_4ynWcPfvm64',
    appId: '1:230534942983:ios:cb6118503239217880b5a2',
    messagingSenderId: '230534942983',
    projectId: 'web-admin-panel-5ebfb',
    storageBucket: 'web-admin-panel-5ebfb.firebasestorage.app',
    iosBundleId: 'com.example.ytEcommerceAdminPanel',
  );
}
